export const motosData = [
  {
    id: 1,
    src: '2022-gold-wing-automatic-dct-matte_nightshade_blue.png',
    href: '/',
    model: '2021 Gold Wing',
    color: 'Cor: Deep pearl gray',
    price: 349,
  },
  {
    id: 2,
    src: '2021-gold-wing-deep_pearl_gray.png',
    href: '/',
    model: '2021 Gold Wing',
    color: 'Cor: Deep pearl gray',
    price: 349,
  },
  {
    id: 3,
    src: 'moto-blue.png',
    href: '/',
    model: '2021 Gold Wing',
    color: 'Cor: Ultra Blue Metallic',
    price: 349,
  },
  {
    id: 4,
    src: '2021-gold-wing-deep_pearl_gray.png',
    href: '/',
    model: '2021 Gold Wing',
    color: 'Cor: Deep pearl gray',
    price: 349,
  },
  {
    id: 5,
    src: 'moto-blue.png',
    href: '/',
    model: '2021 Gold Wing',
    color: 'Cor: Ultra Blue Metallic',
    price: 349,
  },
];
